const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

export const metadata = {
    metadataBase: new URL(baseUrl),
    title: {
        template: "%s | HuyBoonCode",
        default: "HuyBoonCode",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return children;
}
